name: nodflix React Native
on:
  push:
    branches:
      - main
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install npm dependencies
        run: |
          npm install
  build-android:
    needs: install-and-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v1
        with:
          java-version: '17'
      - name: Install npm dependencies
        run: |
          npm install
      - name: Build Android Release
        run: |
          cd android && ./gradlew assembleRelease
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/
      - run: mkdir docs
      - run: mv build/outputs/apk/release/app-release.apk docs/
      - run: cp index.html docs/
      - run: cp README.md docs/
      - run: cp ./android/app/src/main/res/mipmap-hdpi/ic_launcher.png docs/
      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: docs/
      - run: mkdir upload
      - run: cp -r docs upload/
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages
          folder: upload
